/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as MeRouteImport } from './routes/me'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedUsersRouteImport } from './routes/admin/_authed/users'
import { Route as AdminAuthedTasksRouteImport } from './routes/admin/_authed/tasks'
import { Route as AdminAuthedSecurityRouteImport } from './routes/admin/_authed/security'
import { Route as AdminAuthedRobotsRouteImport } from './routes/admin/_authed/robots'
import { Route as AdminAuthedReportsRouteImport } from './routes/admin/_authed/reports'
import { Route as AdminAuthedOpsRouteImport } from './routes/admin/_authed/ops'
import { Route as AdminAuthedMembersRouteImport } from './routes/admin/_authed/members'
import { Route as AdminAuthedInsightRouteImport } from './routes/admin/_authed/insight'
import { Route as AdminAuthedBooksRouteImport } from './routes/admin/_authed/books'
import { Route as AdminAuthedAlertsRouteImport } from './routes/admin/_authed/alerts'
import { Route as AdminAuthedDevTablesRouteImport } from './routes/admin/_authed/dev/tables'
import { Route as AdminAuthedDevServerOpsRouteImport } from './routes/admin/_authed/dev/server-ops'
import { Route as AdminAuthedDevErdRouteImport } from './routes/admin/_authed/dev/erd'
import { Route as AdminAuthedDevArchitectureRouteImport } from './routes/admin/_authed/dev/architecture'
import { Route as AdminAuthedDevApiDocsRouteImport } from './routes/admin/_authed/dev/api-docs'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedUsersRoute = AdminAuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedTasksRoute = AdminAuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSecurityRoute = AdminAuthedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedRobotsRoute = AdminAuthedRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedReportsRoute = AdminAuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedOpsRoute = AdminAuthedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedMembersRoute = AdminAuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedInsightRoute = AdminAuthedInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedBooksRoute = AdminAuthedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedAlertsRoute = AdminAuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevTablesRoute = AdminAuthedDevTablesRouteImport.update({
  id: '/dev/tables',
  path: '/dev/tables',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevServerOpsRoute = AdminAuthedDevServerOpsRouteImport.update({
  id: '/dev/server-ops',
  path: '/dev/server-ops',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevErdRoute = AdminAuthedDevErdRouteImport.update({
  id: '/dev/erd',
  path: '/dev/erd',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevArchitectureRoute =
  AdminAuthedDevArchitectureRouteImport.update({
    id: '/dev/architecture',
    path: '/dev/architecture',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedDevApiDocsRoute = AdminAuthedDevApiDocsRouteImport.update({
  id: '/dev/api-docs',
  path: '/dev/api-docs',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/me': typeof MeRoute
  '/ocr': typeof OcrRoute
  '/recommend': typeof RecommendRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/alerts': typeof AdminAuthedAlertsRoute
  '/admin/books': typeof AdminAuthedBooksRoute
  '/admin/insight': typeof AdminAuthedInsightRoute
  '/admin/members': typeof AdminAuthedMembersRoute
  '/admin/ops': typeof AdminAuthedOpsRoute
  '/admin/reports': typeof AdminAuthedReportsRoute
  '/admin/robots': typeof AdminAuthedRobotsRoute
  '/admin/security': typeof AdminAuthedSecurityRoute
  '/admin/tasks': typeof AdminAuthedTasksRoute
  '/admin/users': typeof AdminAuthedUsersRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/dev/tables': typeof AdminAuthedDevTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/me': typeof MeRoute
  '/ocr': typeof OcrRoute
  '/recommend': typeof RecommendRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/alerts': typeof AdminAuthedAlertsRoute
  '/admin/books': typeof AdminAuthedBooksRoute
  '/admin/insight': typeof AdminAuthedInsightRoute
  '/admin/members': typeof AdminAuthedMembersRoute
  '/admin/ops': typeof AdminAuthedOpsRoute
  '/admin/reports': typeof AdminAuthedReportsRoute
  '/admin/robots': typeof AdminAuthedRobotsRoute
  '/admin/security': typeof AdminAuthedSecurityRoute
  '/admin/tasks': typeof AdminAuthedTasksRoute
  '/admin/users': typeof AdminAuthedUsersRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/dev/tables': typeof AdminAuthedDevTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/me': typeof MeRoute
  '/ocr': typeof OcrRoute
  '/recommend': typeof RecommendRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authed/alerts': typeof AdminAuthedAlertsRoute
  '/admin/_authed/books': typeof AdminAuthedBooksRoute
  '/admin/_authed/insight': typeof AdminAuthedInsightRoute
  '/admin/_authed/members': typeof AdminAuthedMembersRoute
  '/admin/_authed/ops': typeof AdminAuthedOpsRoute
  '/admin/_authed/reports': typeof AdminAuthedReportsRoute
  '/admin/_authed/robots': typeof AdminAuthedRobotsRoute
  '/admin/_authed/security': typeof AdminAuthedSecurityRoute
  '/admin/_authed/tasks': typeof AdminAuthedTasksRoute
  '/admin/_authed/users': typeof AdminAuthedUsersRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/_authed/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/_authed/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/_authed/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/_authed/dev/tables': typeof AdminAuthedDevTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/home'
    | '/login'
    | '/map'
    | '/me'
    | '/ocr'
    | '/recommend'
    | '/scan'
    | '/search'
    | '/settings'
    | '/admin'
    | '/admin/login'
    | '/admin/alerts'
    | '/admin/books'
    | '/admin/insight'
    | '/admin/members'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/robots'
    | '/admin/security'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/'
    | '/admin/dev/api-docs'
    | '/admin/dev/architecture'
    | '/admin/dev/erd'
    | '/admin/dev/server-ops'
    | '/admin/dev/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/home'
    | '/login'
    | '/map'
    | '/me'
    | '/ocr'
    | '/recommend'
    | '/scan'
    | '/search'
    | '/settings'
    | '/admin/login'
    | '/admin/alerts'
    | '/admin/books'
    | '/admin/insight'
    | '/admin/members'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/robots'
    | '/admin/security'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin'
    | '/admin/dev/api-docs'
    | '/admin/dev/architecture'
    | '/admin/dev/erd'
    | '/admin/dev/server-ops'
    | '/admin/dev/tables'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/home'
    | '/login'
    | '/map'
    | '/me'
    | '/ocr'
    | '/recommend'
    | '/scan'
    | '/search'
    | '/settings'
    | '/admin/_authed'
    | '/admin/login'
    | '/admin/_authed/alerts'
    | '/admin/_authed/books'
    | '/admin/_authed/insight'
    | '/admin/_authed/members'
    | '/admin/_authed/ops'
    | '/admin/_authed/reports'
    | '/admin/_authed/robots'
    | '/admin/_authed/security'
    | '/admin/_authed/tasks'
    | '/admin/_authed/users'
    | '/admin/_authed/'
    | '/admin/_authed/dev/api-docs'
    | '/admin/_authed/dev/architecture'
    | '/admin/_authed/dev/erd'
    | '/admin/_authed/dev/server-ops'
    | '/admin/_authed/dev/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MeRoute: typeof MeRoute
  OcrRoute: typeof OcrRoute
  RecommendRoute: typeof RecommendRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/users': {
      id: '/admin/_authed/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthedUsersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/tasks': {
      id: '/admin/_authed/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminAuthedTasksRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/security': {
      id: '/admin/_authed/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminAuthedSecurityRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/robots': {
      id: '/admin/_authed/robots'
      path: '/robots'
      fullPath: '/admin/robots'
      preLoaderRoute: typeof AdminAuthedRobotsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/reports': {
      id: '/admin/_authed/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAuthedReportsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/ops': {
      id: '/admin/_authed/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminAuthedOpsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/members': {
      id: '/admin/_authed/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminAuthedMembersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/insight': {
      id: '/admin/_authed/insight'
      path: '/insight'
      fullPath: '/admin/insight'
      preLoaderRoute: typeof AdminAuthedInsightRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/books': {
      id: '/admin/_authed/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminAuthedBooksRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/alerts': {
      id: '/admin/_authed/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAuthedAlertsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/tables': {
      id: '/admin/_authed/dev/tables'
      path: '/dev/tables'
      fullPath: '/admin/dev/tables'
      preLoaderRoute: typeof AdminAuthedDevTablesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/server-ops': {
      id: '/admin/_authed/dev/server-ops'
      path: '/dev/server-ops'
      fullPath: '/admin/dev/server-ops'
      preLoaderRoute: typeof AdminAuthedDevServerOpsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/erd': {
      id: '/admin/_authed/dev/erd'
      path: '/dev/erd'
      fullPath: '/admin/dev/erd'
      preLoaderRoute: typeof AdminAuthedDevErdRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/architecture': {
      id: '/admin/_authed/dev/architecture'
      path: '/dev/architecture'
      fullPath: '/admin/dev/architecture'
      preLoaderRoute: typeof AdminAuthedDevArchitectureRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/api-docs': {
      id: '/admin/_authed/dev/api-docs'
      path: '/dev/api-docs'
      fullPath: '/admin/dev/api-docs'
      preLoaderRoute: typeof AdminAuthedDevApiDocsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedAlertsRoute: typeof AdminAuthedAlertsRoute
  AdminAuthedBooksRoute: typeof AdminAuthedBooksRoute
  AdminAuthedInsightRoute: typeof AdminAuthedInsightRoute
  AdminAuthedMembersRoute: typeof AdminAuthedMembersRoute
  AdminAuthedOpsRoute: typeof AdminAuthedOpsRoute
  AdminAuthedReportsRoute: typeof AdminAuthedReportsRoute
  AdminAuthedRobotsRoute: typeof AdminAuthedRobotsRoute
  AdminAuthedSecurityRoute: typeof AdminAuthedSecurityRoute
  AdminAuthedTasksRoute: typeof AdminAuthedTasksRoute
  AdminAuthedUsersRoute: typeof AdminAuthedUsersRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedDevApiDocsRoute: typeof AdminAuthedDevApiDocsRoute
  AdminAuthedDevArchitectureRoute: typeof AdminAuthedDevArchitectureRoute
  AdminAuthedDevErdRoute: typeof AdminAuthedDevErdRoute
  AdminAuthedDevServerOpsRoute: typeof AdminAuthedDevServerOpsRoute
  AdminAuthedDevTablesRoute: typeof AdminAuthedDevTablesRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedAlertsRoute: AdminAuthedAlertsRoute,
  AdminAuthedBooksRoute: AdminAuthedBooksRoute,
  AdminAuthedInsightRoute: AdminAuthedInsightRoute,
  AdminAuthedMembersRoute: AdminAuthedMembersRoute,
  AdminAuthedOpsRoute: AdminAuthedOpsRoute,
  AdminAuthedReportsRoute: AdminAuthedReportsRoute,
  AdminAuthedRobotsRoute: AdminAuthedRobotsRoute,
  AdminAuthedSecurityRoute: AdminAuthedSecurityRoute,
  AdminAuthedTasksRoute: AdminAuthedTasksRoute,
  AdminAuthedUsersRoute: AdminAuthedUsersRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedDevApiDocsRoute: AdminAuthedDevApiDocsRoute,
  AdminAuthedDevArchitectureRoute: AdminAuthedDevArchitectureRoute,
  AdminAuthedDevErdRoute: AdminAuthedDevErdRoute,
  AdminAuthedDevServerOpsRoute: AdminAuthedDevServerOpsRoute,
  AdminAuthedDevTablesRoute: AdminAuthedDevTablesRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MeRoute: MeRoute,
  OcrRoute: OcrRoute,
  RecommendRoute: RecommendRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
